### ISSUE TITLE
Windows(MINGW)でdtsmのセットアップに失敗する

### ISSUE THREAD

**Issue by nureha** [vvakame/angularjs-typescript#2]
http://qiita.com/nureha/items/1a503247ae75e5324b66#comment-61fa6ffb6919dd8b3033
こちらにてアドバイスいただいた通り試してみましたがやはり同様のエラーが出ました。

```
grunt-dtsm@0.2.9 node_modules\grunt-dtsm
├── es6-promise@2.3.0
└── dtsm@0.10.3 (archy@1.0.0, fs-git@0.4.1, which@1.1.1, mkdirp@0.5.1, commandpost@0.1.1, rimraf@2.3.4, packagemanager-backend@0.6.5, es6-promise@2.1.1, update-notifier@0.5.0, insight@0.6.0)
```

こちらのログ及びgrunt-dtsmのpackage.jsonを見る限り0.2.9になっているように見えます。

**Comment by vvakame** [comment]
ありがとうございます。
Windows環境+MinGW環境をなんとか確保してみます…(すぐには対応できないと思います

**Comment by vvakame** [comment]
@nureha あ、すみませんNode.jaのバージョンはいくつでしょうか？ `node -v` の結果を教えてほしいです。(前dtsmに入れたWindows対応、そういえばNode.js 0.12以降じゃないとうまく動かないかもです…)

**Comment by nureha** [comment]
@vvakame 
```
$ node -v
v0.10.28
```
でした。。。
バージョンアップして再試行してみます。

**Comment by nureha** [comment]
@vvakame 
v0.12.7にて無事完了しました！
ありがとうございます。

**Comment by vvakame** [comment]
よかったです！Node.js 0.10系で実行した時に何か出したほうがいいかもしれないですね…。
